import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/introduction-welcome',
      ],
    },
    {
      type: 'category',
      label: '1NCE Portal',
      items: [
        '1nce-portal/portal-dashboard',
        '1nce-portal/portal-sims-sms',
        '1nce-portal/portal-configuration',
        '1nce-portal/portal-accounts-orders',
        '1nce-portal/portal-users-organisations',
        '1nce-portal/portal-performance-support',
      ],
    },
    {
      type: 'category',
      label: 'SIM Cards',
      items: [
        'sim-cards/sim-cards-knowledge',
        'sim-cards/sim-euicc-knowledge',
        {
          type: 'category',
          label: '1NCE Brazil Multi Imsi',
          link: { type: 'doc', id: 'sim-cards/1nce-brazil-multi-imsi/index' },
          items: [
            'sim-cards/1nce-brazil-multi-imsi/1nce-brazil-feature-description',
            'sim-cards/1nce-brazil-multi-imsi/1nce-brazil-switching-and-requirements',
          ],
        },
        {
          type: 'category',
          label: 'Sim Cards Overview',
          link: { type: 'doc', id: 'sim-cards/sim-cards-overview/index' },
          items: [
            'sim-cards/sim-cards-overview/sim-cards-iot-business',
            'sim-cards/sim-cards-overview/sim-cards-iot-industrial',
            'sim-cards/sim-cards-overview/sim-chips-iot-industrial',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP Server',
      items: [
        'mcp-server/mcp',
      ],
    },
    {
      type: 'category',
      label: 'Connectivity Services',
      items: [
        'connectivity-services/connectivity-services-no-harm-network',
        {
          type: 'category',
          label: 'Connectivity Services Mobile Network Services',
          link: { type: 'doc', id: 'connectivity-services/connectivity-services-mobile-network-services/index' },
          items: [
            'connectivity-services/connectivity-services-mobile-network-services/mobile-network-services-coverage',
            'connectivity-services/connectivity-services-mobile-network-services/mobile-network-services-discontinuation',
          ],
        },
        {
          type: 'category',
          label: 'Connectivity Services Data Services',
          link: { type: 'doc', id: 'connectivity-services/connectivity-services-data-services/index' },
          items: [
            'connectivity-services/connectivity-services-data-services/data-services-features-limitations',
            'connectivity-services/connectivity-services-data-services/data-services-apn',
            'connectivity-services/connectivity-services-data-services/data-services-data-monitoring',
            'connectivity-services/connectivity-services-data-services/data-services-data-volume',
          ],
        },
        {
          type: 'category',
          label: 'Connectivity Services SMS Services',
          link: { type: 'doc', id: 'connectivity-services/connectivity-services-sms-services/index' },
          items: [
            'connectivity-services/connectivity-services-sms-services/sms-services-features-limitations',
            'connectivity-services/connectivity-services-sms-services/sms-services-mt-sms',
            'connectivity-services/connectivity-services-sms-services/sms-services-mo-sms',
            'connectivity-services/connectivity-services-sms-services/sms-services-sms-monitoring',
            'connectivity-services/connectivity-services-sms-services/sms-services-sms-volume',
            'connectivity-services/connectivity-services-sms-services/sms-services-examples',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Services',
      items: [
        {
          type: 'category',
          label: 'Platform Services SMS Forwarder',
          link: { type: 'doc', id: 'platform-services/platform-services-sms-forwarder/index' },
          items: [
            'platform-services/platform-services-sms-forwarder/sms-forwarder-features-limitations',
            'platform-services/platform-services-sms-forwarder/sms-forwarder-events',
            'platform-services/platform-services-sms-forwarder/sms-forwarder-error-states',
            'platform-services/platform-services-sms-forwarder/sms-forwarder-setup-guides',
          ],
        },
        {
          type: 'category',
          label: 'Platform Services Data Streamer',
          link: { type: 'doc', id: 'platform-services/platform-services-data-streamer/index' },
          items: [
            'platform-services/platform-services-data-streamer/data-streamer-features-limitations',
            'platform-services/platform-services-data-streamer/data-streamer-event-records',
            'platform-services/platform-services-data-streamer/data-streamer-usage-records',
            'platform-services/platform-services-data-streamer/data-streamer-setup-guides',
          ],
        },
        'platform-services/platform-services-blockchain',
      ],
    },
    {
      type: 'category',
      label: 'Network Services',
      items: [
        'network-services/network-services-internet-breakout',
        {
          type: 'category',
          label: 'Network Services VPN Service',
          link: { type: 'doc', id: 'network-services/network-services-vpn-service/index' },
          items: [
            'network-services/network-services-vpn-service/vpn-service-features-limitations',
            'network-services/network-services-vpn-service/vpn-service-openvpn-files',
            'network-services/network-services-vpn-service/vpn-service-setup-guides',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '1NCE OS',
      items: [
        {
          type: 'category',
          label: '1NCE OS Services Overview',
          link: { type: 'doc', id: '1nce-os/1nce-os-services-overview/index' },
          items: [
            '1nce-os/1nce-os-services-overview/1nce-os-terms-of-use',
            '1nce-os/1nce-os-services-overview/1nce-os-data-processing-agreement',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Device Authenticator',
          link: { type: 'doc', id: '1nce-os/1nce-os-device-authenticator/index' },
          items: [
            '1nce-os/1nce-os-device-authenticator/device-authenticator-features-limitations',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Device Controller',
          link: { type: 'doc', id: '1nce-os/1nce-os-device-controller/index' },
          items: [
            '1nce-os/1nce-os-device-controller/device-controller-features-limitations',
            '1nce-os/1nce-os-device-controller/device-controller-web-interface',
            '1nce-os/1nce-os-device-controller/device-controller-api',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Device Integrator',
          link: { type: 'doc', id: '1nce-os/1nce-os-device-integrator/index' },
          items: [
            '1nce-os/1nce-os-device-integrator/device-integrator-udp',
            '1nce-os/1nce-os-device-integrator/device-integrator-coap',
            '1nce-os/1nce-os-device-integrator/device-integrator-test-endpoints',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Plugins',
          link: { type: 'doc', id: '1nce-os/1nce-os-plugins/index' },
          items: [
            '1nce-os/1nce-os-plugins/1nce-os-plugins-features-limitations',
            '1nce-os/1nce-os-plugins/1nce-os-plugins-data-visualization-datacake',
            '1nce-os/1nce-os-plugins/1nce-os-plugins-fota-management-mender',
            '1nce-os/1nce-os-plugins/1nce-os-plugins-azure-integration-tartabit',
            '1nce-os/1nce-os-plugins/1nce-os-plugins-device-observability-memfault',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS LWM2M',
          link: { type: 'doc', id: '1nce-os/1nce-os-lwm2m/index' },
          items: [
            '1nce-os/1nce-os-lwm2m/lwm2m-features-limitations',
            '1nce-os/1nce-os-lwm2m/lwm2m-bootstrapping',
            '1nce-os/1nce-os-lwm2m/lwm2m-data-handling',
            '1nce-os/1nce-os-lwm2m/lwm2m-device-locator-integration',
            '1nce-os/1nce-os-lwm2m/lwm2m-client-examples',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Cloud Integrator',
          link: { type: 'doc', id: '1nce-os/1nce-os-cloud-integrator/index' },
          items: [
            '1nce-os/1nce-os-cloud-integrator/cloud-integrator-features-limitations',
            '1nce-os/1nce-os-cloud-integrator/cloud-integrator-aws-configuration',
            '1nce-os/1nce-os-cloud-integrator/cloud-integrator-webhook-configuration',
            '1nce-os/1nce-os-cloud-integrator/cloud-integrator-failure-event',
            '1nce-os/1nce-os-cloud-integrator/cloud-integrator-output-format',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Device Inspector',
          link: { type: 'doc', id: '1nce-os/1nce-os-device-inspector/index' },
          items: [
            '1nce-os/1nce-os-device-inspector/device-inspector-features-limitations',
            '1nce-os/1nce-os-device-inspector/device-inspector-historian-web-interface',
            '1nce-os/1nce-os-device-inspector/device-inspector-historian-api',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Device Locator',
          link: { type: 'doc', id: '1nce-os/1nce-os-device-locator/index' },
          items: [
            '1nce-os/1nce-os-device-locator/device-locator-features-limitations',
            '1nce-os/1nce-os-device-locator/device-locator-geofencing-guide',
            '1nce-os/1nce-os-device-locator/device-locator-api',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Energy Saver',
          link: { type: 'doc', id: '1nce-os/1nce-os-energy-saver/index' },
          items: [
            '1nce-os/1nce-os-energy-saver/energy-saver-features-limitations',
            '1nce-os/1nce-os-energy-saver/energy-saver-binary-conversion-language',
            '1nce-os/1nce-os-energy-saver/energy-saver-template-tester',
            '1nce-os/1nce-os-energy-saver/energy-saver-energy-saved-calculation',
            '1nce-os/1nce-os-energy-saver/energy-saver-device-locator-integration',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS Admin Logs',
          link: { type: 'doc', id: '1nce-os/1nce-os-admin-logs/index' },
          items: [
            '1nce-os/1nce-os-admin-logs/admin-logs-features-limitations',
            '1nce-os/1nce-os-admin-logs/admin-logs-web-interface',
            '1nce-os/1nce-os-admin-logs/admin-logs-api',
            '1nce-os/1nce-os-admin-logs/admin-logs-info-category',
          ],
        },
        {
          type: 'category',
          label: '1NCE OS SDK Blueprints',
          link: { type: 'doc', id: '1nce-os/1nce-os-sdk-blueprints/index' },
          items: [
            '1nce-os/1nce-os-sdk-blueprints/sdk-blueprints-arduino',
            '1nce-os/1nce-os-sdk-blueprints/sdk-blueprints-freertos',
            '1nce-os/1nce-os-sdk-blueprints/sdk-blueprints-zephyr',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        'troubleshooting/troubleshooting-technical-support',
      ],
    },
    {
      type: 'category',
      label: 'Blueprints & Examples',
      items: [
        'blueprints-examples/wvdial-tutorial',
        'blueprints-examples/1nce-vpn-linux-client',
        'blueprints-examples/sim800l-network-registration',
        'blueprints-examples/sim800l-icmp-ping',
        'blueprints-examples/sim800l-mo-sms',
        'blueprints-examples/sim800l-mt-sms',
        'blueprints-examples/sim800l-tcp-client-connection',
        'blueprints-examples/sim800l-udp-client-connection',
        'blueprints-examples/sim800l-http-get',
        'blueprints-examples/sim800l-http-post',
        'blueprints-examples/sim7000g-rat-configuration',
        'blueprints-examples/sim7000g-network-registration',
        'blueprints-examples/sim7000g-icmp-ping',
        'blueprints-examples/sim7000g-mo-sms',
        'blueprints-examples/sim7000g-mt-sms',
        'blueprints-examples/sim7000g-tcp-client-connection',
        'blueprints-examples/sim7000g-udp-client-connection',
        'blueprints-examples/sim7000g-http-get',
        'blueprints-examples/sim7000g-http-post',
        'blueprints-examples/sim7000g-ftp-get',
        'blueprints-examples/ec25-rat-configuration',
        'blueprints-examples/ec25-network-registration',
        'blueprints-examples/ec25-icmp-ping',
        'blueprints-examples/ec25-mo-sms',
        'blueprints-examples/ec25-mt-sms',
        'blueprints-examples/ec25-tcp-client-connection',
        'blueprints-examples/bg95-m3-network-registration',
        'blueprints-examples/bg95-m3-icmp-ping',
        'blueprints-examples/bg95-m3-1nce-os-udp',
        'blueprints-examples/bg95bg77-tcp-client-connection',
        'blueprints-examples/ec25-ec21-1nce-os-udp',
        'blueprints-examples/sim7020e-1nce-os-coap',
        'blueprints-examples/sim7000g-1nce-os-udp',
        'blueprints-examples/sim7000g-1nce-os-coap',
        'blueprints-examples/sara-r410m-network-registration',
        'blueprints-examples/sara-r410m-1nce-os-udp',
        'blueprints-examples/sara-r4-get-http',
        'blueprints-examples/sim7020e-1nce-os-coap-1',
        {
          type: 'category',
          label: 'Examples Data Streamer',
          link: { type: 'doc', id: 'blueprints-examples/examples-data-streamer/index' },
          items: [
            'blueprints-examples/examples-data-streamer/examples-data-streamer-http',
            'blueprints-examples/examples-data-streamer/examples-data-streamer-s3',
            'blueprints-examples/examples-data-streamer/examples-data-streamer-kinesis',
            'blueprints-examples/examples-data-streamer/examples-data-streamer-keen',
            'blueprints-examples/examples-data-streamer/examples-data-streamer-datadog',
          ],
        },
        'blueprints-examples/examples-hardware-guides',
        'blueprints-examples/examples-overview',
        {
          type: 'category',
          label: 'Examples SMS',
          link: { type: 'doc', id: 'blueprints-examples/examples-sms/index' },
          items: [
            'blueprints-examples/examples-sms/examples-mt-sms',
            'blueprints-examples/examples-sms/examples-mo-sms',
          ],
        },
        {
          type: 'category',
          label: 'Examples SMS Forwarder',
          link: { type: 'doc', id: 'blueprints-examples/examples-sms-forwarder/index' },
          items: [
            'blueprints-examples/examples-sms-forwarder/examples-sms-forwarder-portal',
            'blueprints-examples/examples-sms-forwarder/examples-sms-forwarder-testing',
          ],
        },
        {
          type: 'category',
          label: 'Examples VPN',
          link: { type: 'doc', id: 'blueprints-examples/examples-vpn/index' },
          items: [
            'blueprints-examples/examples-vpn/examples-vpn-windows',
            'blueprints-examples/examples-vpn/examples-vpn-linux',
            'blueprints-examples/examples-vpn/examples-vpn-macos',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        'quectel-bg95-m3',
        'quectel-ec25-ec21',
        'recipes',
        'sara-r410m',
        'sim7000g',
        'simcom-7020g-simcom800l',
        'terms-abbreviations',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'category',
          label: 'Readmeconfig',
          items: [
            'reference/readmeconfig/getting-started',
            'reference/readmeconfig/authentication',
            'reference/readmeconfig/my-requests',
          ],
        },
        {
          type: 'category',
          label: 'API Introduction',
          items: [
            'reference/api-introduction/api-welcome',
            'reference/api-introduction/api-best-practices',
            'reference/api-introduction/api-rate-limits',
            'reference/api-introduction/api-authorization',
          ],
        },
        {
          type: 'category',
          label: 'MCP Server',
          items: [
            'reference/mcp-server/mcp',
          ],
        },
        {
          type: 'category',
          label: 'Authorization',
          items: [
            {
              type: 'category',
              label: 'Bearer Authorization',
              link: { type: 'doc', id: 'reference/authorization/bearer-authorization/index' },
              items: [
                'reference/authorization/bearer-authorization/postaccesstokenpost',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Sim Management',
          items: [
            {
              type: 'category',
              label: 'General Sims',
              link: { type: 'doc', id: 'reference/sim-management/general-sims/index' },
              items: [
                'reference/sim-management/general-sims/getsimsusingget',
                'reference/sim-management/general-sims/updatesimsusingpost',
                'reference/sim-management/general-sims/getsimusingget',
                'reference/sim-management/general-sims/updatesimusingput',
                'reference/sim-management/general-sims/getstatusforsimusingget',
                'reference/sim-management/general-sims/simtransferusingpost',
              ],
            },
            {
              type: 'category',
              label: 'SMS',
              link: { type: 'doc', id: 'reference/sim-management/sms/index' },
              items: [
                'reference/sim-management/sms/getsmsforsimusingget',
                'reference/sim-management/sms/sendsmstosimusingpost',
                'reference/sim-management/sms/getsmsofsimusingget',
                'reference/sim-management/sms/cancelsmsforsimusingdelete',
              ],
            },
            {
              type: 'category',
              label: 'Connectivity',
              link: { type: 'doc', id: 'reference/sim-management/connectivity/index' },
              items: [
                'reference/sim-management/connectivity/getconnectivityinfoforsimusingget',
                'reference/sim-management/connectivity/resetconnectivityusingpost',
              ],
            },
            {
              type: 'category',
              label: 'Sim Events',
              link: { type: 'doc', id: 'reference/sim-management/sim-events/index' },
              items: [
                'reference/sim-management/sim-events/geteventsforsimusingget',
              ],
            },
            {
              type: 'category',
              label: 'Sim Usage',
              link: { type: 'doc', id: 'reference/sim-management/sim-usage/index' },
              items: [
                'reference/sim-management/sim-usage/getusageforsimusingget',
                'reference/sim-management/sim-usage/getdataquotaforsimusingget',
                'reference/sim-management/sim-usage/getsmsquotaforsimusingget',
              ],
            },
            {
              type: 'category',
              label: 'Volume Limits',
              link: { type: 'doc', id: 'reference/sim-management/volume-limits/index' },
              items: [
                'reference/sim-management/volume-limits/getlimitsusingget',
                'reference/sim-management/volume-limits/setlimitsusingpost',
                'reference/sim-management/volume-limits/getselectablelimitsusingget',
              ],
            },
            {
              type: 'category',
              label: 'Volume Top Up',
              link: { type: 'doc', id: 'reference/sim-management/volume-top-up/index' },
              items: [
                'reference/sim-management/volume-top-up/topupusingpost',
                'reference/sim-management/volume-top-up/topupmultipleusingpost',
                'reference/sim-management/volume-top-up/autotopupusingpost',
              ],
            },
            {
              type: 'category',
              label: 'Sim Extension',
              link: { type: 'doc', id: 'reference/sim-management/sim-extension/index' },
              items: [
                'reference/sim-management/sim-extension/extendsimsusingpost',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Order Management',
          items: [
            {
              type: 'category',
              label: 'Orders',
              link: { type: 'doc', id: 'reference/order-management/orders/index' },
              items: [
                'reference/order-management/orders/getordersusingget',
                'reference/order-management/orders/postorderusingpost',
                'reference/order-management/orders/getorderusingget',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Support Management',
          items: [
            {
              type: 'category',
              label: 'Service Requests',
              link: { type: 'doc', id: 'reference/support-management/service-requests/index' },
              items: [
                'reference/support-management/service-requests/getservicerequestsusingget',
                'reference/support-management/service-requests/createservicerequestusingpost',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Product Information',
          items: [
            {
              type: 'category',
              label: 'Products',
              link: { type: 'doc', id: 'reference/product-information/products/index' },
              items: [
                'reference/product-information/products/getproductsusingget',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '1NCE OS',
          items: [
            {
              type: 'category',
              label: 'Iot Integrator',
              link: { type: 'doc', id: 'reference/1nce-os/iot-integrator/index' },
              items: [
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-endpoints',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-endpoints-protocol',
                'reference/1nce-os/iot-integrator/patch_v1-integrate-devices-endpoints-protocol',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-actions-requests',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-actions-requests-active',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-actions-requests-archived',
                'reference/1nce-os/iot-integrator/delete_v1-integrate-devices-deviceid-actions-requests',
                'reference/1nce-os/iot-integrator/delete_v1-integrate-devices-actions-requests-requestid',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-actions-requests-requestid',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-deviceid-presharedkey',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-presharedkey-jobs',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-presharedkey-jobs',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-deviceid-psk',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-deviceid-psk-protocol',
                'reference/1nce-os/iot-integrator/get_v1-integrate-devices-psk-jobs',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-psk-jobs',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-deviceid-actions-lwm2m',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-actions-lwm2m',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-deviceid-actions-coap',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-actions-coap',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-deviceid-actions-udp',
                'reference/1nce-os/iot-integrator/post_v1-integrate-devices-actions-udp',
                'reference/1nce-os/iot-integrator/get_v1-integrate-clouds-aws-parameters',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-aws-integrationid-restart',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-aws-integrationid-test',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-aws',
                'reference/1nce-os/iot-integrator/delete_v1-integrate-clouds-integrationid',
                'reference/1nce-os/iot-integrator/get_v1-integrate-clouds-integrationid',
                'reference/1nce-os/iot-integrator/patch_v1-integrate-clouds-integrationid',
                'reference/1nce-os/iot-integrator/get_v1-integrate-clouds',
                'reference/1nce-os/iot-integrator/get_v1-integrate-clouds-eventtypes',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-webhooks',
                'reference/1nce-os/iot-integrator/patch_v1-integrate-clouds-webhooks-integrationid',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-webhooks-integrationid-restart',
                'reference/1nce-os/iot-integrator/post_v1-integrate-clouds-webhooks-integrationid-test',
              ],
            },
            {
              type: 'category',
              label: 'Optimizer',
              link: { type: 'doc', id: 'reference/1nce-os/optimizer/index' },
              items: [
                'reference/1nce-os/optimizer/post_v1-optimize-messages-test',
                'reference/1nce-os/optimizer/get_v1-optimize-savings',
                'reference/1nce-os/optimizer/get_v1-optimize-templates',
                'reference/1nce-os/optimizer/post_v1-optimize-templates',
                'reference/1nce-os/optimizer/delete_v1-optimize-templates-templateid',
                'reference/1nce-os/optimizer/patch_v1-optimize-templates-templateid',
              ],
            },
            {
              type: 'category',
              label: 'Device Inspector',
              link: { type: 'doc', id: 'reference/1nce-os/device-inspector/index' },
              items: [
                'reference/1nce-os/device-inspector/get_v1-inspect-devices',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-deviceid',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-deviceid-telemetry',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-deviceid-history',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-history',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-deviceid-history-insights',
                'reference/1nce-os/device-inspector/get_v1-inspect-devices-history-insights',
              ],
            },
            {
              type: 'category',
              label: 'Device Locator',
              link: { type: 'doc', id: 'reference/1nce-os/device-locator/index' },
              items: [
                'reference/1nce-os/device-locator/get_v1-locate-devices-deviceid-positions',
                'reference/1nce-os/device-locator/get_v1-locate-positions-latest',
                'reference/1nce-os/device-locator/get_v1-locate-devices-deviceid-activity',
                'reference/1nce-os/device-locator/get_v1-locate-geofences',
                'reference/1nce-os/device-locator/post_v1-locate-geofences',
                'reference/1nce-os/device-locator/delete_v1-locate-geofences-geofenceid',
                'reference/1nce-os/device-locator/get_v1-locate-geofences-geofenceid',
                'reference/1nce-os/device-locator/patch_v1-locate-geofences-geofenceid',
              ],
            },
            {
              type: 'category',
              label: 'Agreements',
              link: { type: 'doc', id: 'reference/1nce-os/agreements/index' },
              items: [
                'reference/1nce-os/agreements/post_v1-agreements-1nceos',
              ],
            },
            {
              type: 'category',
              label: 'Administration Logs',
              link: { type: 'doc', id: 'reference/1nce-os/administration-logs/index' },
              items: [
                'reference/1nce-os/administration-logs/get_v1-administrationlogs',
                'reference/1nce-os/administration-logs/get_v1-administrationlogs-stats',
                'reference/1nce-os/administration-logs/get_v1-administrationlogs-adminlogid-payload',
              ],
            },
            {
              type: 'category',
              label: 'Devices',
              link: { type: 'doc', id: 'reference/1nce-os/devices/index' },
              items: [
                'reference/1nce-os/devices/post_v1-devices-deviceid-actions',
                'reference/1nce-os/devices/get_v1-devices-stats',
              ],
            },
            {
              type: 'category',
              label: 'Settings',
              link: { type: 'doc', id: 'reference/1nce-os/settings/index' },
              items: [
                'reference/1nce-os/settings/patch_v1-settings-1nceos-name',
                'reference/1nce-os/settings/get_v1-settings-1nceos',
              ],
            },
            {
              type: 'category',
              label: 'Plugin System',
              link: { type: 'doc', id: 'reference/1nce-os/plugin-system/index' },
              items: [
                'reference/1nce-os/plugin-system/post_v1-partners-datacake-plugins',
                'reference/1nce-os/plugin-system/post_v1-partners-mender-plugins',
                'reference/1nce-os/plugin-system/post_v1-partners-tartabit-plugins',
                'reference/1nce-os/plugin-system/post_v1-partners-memfault-plugins',
                'reference/1nce-os/plugin-system/delete_v1-partners-plugins-pluginid',
                'reference/1nce-os/plugin-system/get_v1-partners-plugins-pluginid',
                'reference/1nce-os/plugin-system/post_v1-partners-plugins-pluginid-restart',
                'reference/1nce-os/plugin-system/get_v1-partners-plugins',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
